### ISSUE TITLE
Deploying nuxt app over netlify edge functions throws error at build

### ISSUE THREAD

**Issue by officialpiyush** [vuejs/vuefire#1284]
### Reproduction

repo is private, can give access to the repository if needed

### Steps to reproduce the bug

- install and configure `nuxt-vuefire` module
- make sure `ssr` is not set to false
- build the application for `netlify-edge` / `cloudflare-pages` channel

This is how I configured my application
```ts
[
  'nuxt-vuefire',
  {
    auth: true,
    config: {
		// ..apiKey, authDomain, etc stuff from firebase
    },
    admin: {
      config: JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT as string),
    },
  } as VueFireNuxtModuleOptions,
]
```

### Expected behavior

The build should be completed without any issues.

### Actual behavior

The build fails with the following stack:

```
 ERROR                                                                                                                                                               nitro 00:56:53

1: import * as http from 'http';
2: import * as https from 'https';
3: import { once } from 'events';
            ^
4: import { JOSEError, JWKSTimeout } from '../util/errors.js';
5: import { concat, decoder } from '../lib/buffer_utils.js';


 ERROR  'once' is not exported by node_modules/.pnpm/unenv@1.0.0/node_modules/unenv/runtime/node/events/index.mjs, imported by node_modules/.pnpm/jose@4.11.2/node_modules/jose/dist/node/esm/runtime/fetch_jwks.js

  at error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
  at ReturnValueScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at Identifier.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
  at ArrayExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
  at AwaitExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclarator.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclaration.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at BlockStatement.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at ArrowFunctionExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclarator.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclaration.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at Program.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
  at Module.bindReferences (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12425:18)
  at Graph.sortModules (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23062:20)
  at Graph.build (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22940:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23730:13
  at async catchUnfinishedHookActions (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23126:20)
  at async rollupInternal (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23727:5)
  at async _build (node_modules/.pnpm/nitropack@1.0.0/node_modules/nitropack/dist/shared/nitro.c8278d90.mjs:1404:18)
  at async node_modules/.pnpm/nuxt@3.0.0_e3uo4sehh4zr4i6m57mkkxxv7y/node_modules/nuxt/dist/index.mjs:1677:9
  at async build (node_modules/.pnpm/nuxt@3.0.0_e3uo4sehh4zr4i6m57mkkxxv7y/node_modules/nuxt/dist/index.mjs:2236:5)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/build.mjs:56:5)
  at async _main (node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/cli.mjs:50:20)
```

### Additional information

The documentation mentions that SSR is partially supported, and to open an issue if we find any.
It is also noteworthy that the 2022 roadmap (#1241) mentions to explore other channels such as netlify and vercel.

I was able to build the application by removing `nuxt-vuefire` from nuxt modules, so the issue is from this module only.

**Comment by officialpiyush** [comment]
came across https://github.com/firebase/firebase-admin-node/issues/1801, seems like the firebase team is not planning on adding support for edge runtimes anytime soon

**Comment by officialpiyush** [comment]
Also related: https://github.com/unjs/unenv/issues/54

**Comment by dosstx** [comment]
I'm having trouble getting a Nuxt app that uses Firebase to deploy using Netlify Edge. From what I read in this thread, it seems that using `firebase-admin` is not compatible with Netlify Edge Deno runtime? Does that mean I can not use the `nuxt-vuefire` module ? Please let me know if my understanding is correct.

**Comment by officialpiyush** [comment]
> I'm having trouble getting a Nuxt app that uses Firebase to deploy using Netlify Edge. From what I read in this thread, it seems that using `firebase-admin` is not compatible with Netlify Edge Deno runtime? Does that mean I can not use the `nuxt-vuefire` module ? Please let me know if my understanding is correct.

Yes I suppose, as per the [issue I linked from the firebase-admin repo](https://github.com/firebase/firebase-admin-node/issues/1801), it seems like the firebase-admin team is not planning to add edge support soon.

You can still use client side firebase features with SSR disabled afaik

**Comment by dosstx** [comment]
@posva or anyone:

Since we can't use Nuxt Vuefire on an Edge Function runtime, is there a way we can somehow still check for a user in middleware? 

For instance, in the docs you have this:

```
// middleware/auth.ts
export default defineNuxtRouteMiddleware(async (to, from) => {
  const user = await getCurrentUser()

  // redirect the user to the login page
  if (!user) {
    return navigateTo({
      path: '/login',
      query: {
        redirect: to.fullPath,
      },
    })
  }
})
```

But that won't work on Edge runtimes because I think that requires Firebase Admin SDK and it is Node only. Is there another way to somehow check/get current user so it doesn't require Firebase Admin ? Would the nuxt-vuefire module still be needed? Or, should I wrap the regular VueFire as a plugin and not use Nuxt-Vuefire in Nuxt for this case?

Seeking guidance. Thank you.
