### ISSUE TITLE
Cannot find module './URL' Require stack : [...]whatwg-url

### ISSUE THREAD

**Issue by noook** [vuejs/vuefire#1331]
### Reproduction

https://github.com/noook/nuxt-vuefire-repro

### Steps to reproduce the bug

1.  Fresh install Nuxt `npx nuxi@latest init project-name`
2. Install `nuxt-vuefire` and every dependency
3. Register plugin in `nuxt.config.ts`
4. Run the server
5. Load the first page

### Expected behavior

Should open the page

### Actual behavior

a 500 error is thrown:

Node 18:
```
Cannot find module './URL' Require stack: - /Users/nook/work/vuefire-service/whatwg-url

at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
at Module._load (node:internal/modules/cjs/loader:920:27)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at ./whatwg-url:3:15
at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:315:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:159:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:207:14)
at async ./node-fetch:7:31
```

Node 16:
```
Cannot find module './URL' Require stack: - /Users/nook/work/vuefire-service/whatwg-url

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
at Function.Module._load (node:internal/modules/cjs/loader:866:27)
at Module.require (node:internal/modules/cjs/loader:1093:19)
at require (node:internal/modules/cjs/helpers:108:18)
at ./whatwg-url:3:15
at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:315:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:159:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:207:14)
at async ./node-fetch:7:31
```

### Additional information

I tried on both node 16 and 18

**Update:**
I also tried without firebase installed in the project (I started with the regular Vue getting started, now I only did the Nuxt one) and I am getting a different error:
```
Cannot find module './websocket/api' Require stack: - /Users/nook/work/vuefire-service/faye-websocket

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
at Function.Module._load (node:internal/modules/cjs/loader:866:27)
at Module.require (node:internal/modules/cjs/loader:1093:19)
at require (node:internal/modules/cjs/helpers:108:18)
at ./faye-websocket:11:14
at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:315:11)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:159:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:207:14)
```

**Comment by Watster69** [comment]
I'm also seeing this issue. The module is completely unusable.

**Comment by bogdanciuca** [comment]
Looks like it occurs when `ssr: true`, which is the default. [vuefire-nuxt-example](https://github.com/posva/vuefire-nuxt-example/blob/main/nuxt.config.ts#L6) offers some explanation.

**Comment by posva** [comment]
it's fixed and released now! Turns out vuefire was still relying on some workarounds for Nuxt 3.0.0 and they broke in newer versions
