### ISSUE TITLE
The default Firebase app does not exist. Make sure you call initializeApp()

### ISSUE THREAD

**Issue by crunchwrap89** [vuejs/vuefire#1403]
### Reproduction

*

### Steps to reproduce the bug

1. Update to latest version of firebase firebase-admin vuefire & nuxt-vuefire.
2. Enable auth
3. Run app with SSR enabled

### Expected behavior

Application starts, initializeApp from firebase-admin should not be needed (?)

### Actual behavior

Application cannot start: 

```
✔ Vite server hmr 12 files in 135.548ms                                                                                                                                                                                                 6:57:36 PM
[nuxt] [request error] [unhandled] [500] The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.                                                                          6:57:36 PM
  at AppStore.getApp (./node_modules/firebase-admin/lib/app/lifecycle.js:65:19)  
  at getApp (./node_modules/firebase-admin/lib/app/lifecycle.js:106:36)  
  at Module.getAuth (./node_modules/firebase-admin/lib/auth/index.js:50:34)  
  at ./node_modules/nuxt-vuefire/dist/runtime/auth/plugin.server.mjs:19:43  
  at ./node_modules/nuxt/dist/app/nuxt.js:112:60  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:156:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
  at ./node_modules/nuxt/dist/app/nuxt.js:158:56  
  at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:158:24)

```

### Additional information

Tried manually adding "initializeApp()" from firebase-admin and initialized in App.vue, also tried adding it to my auth middleware:

```
import { initializeApp } from "firebase-admin";
import { getApps } from "firebase-admin/app";

export default defineNuxtRouteMiddleware(async (to) => {
  if (getApps().length === 0) {
    console.log("initialize app");
    initializeApp();
  }
 ...
```

**Comment by posva** [comment]
I cannot check without a repro

**Comment by posva** [comment]
I added a template to create the bug report: https://github.com/posva/nuxt--vuefire-repro-template

But I think you are just missing the credentials: https://vuefire.vuejs.org/nuxt/getting-started.html#Configuring-the-Admin-SDK

**Comment by anthony32773** [comment]
I am also experiencing this as well.

**Comment by posva** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with a reproduction so I can check.

I'm adding some templates with long instructions on how to provision firebase, in case anybody found them useful.

- https://github.com/posva/nuxt--vuefire-example-spark-plan

I'm still waiting for upstream changes for the blaze plan onee

---

Please, don't comment to just say +1, it doesn't help in finding the problem...
