### ISSUE TITLE
TypeError: e.key is not a function with Firebase 3 and Vuefire 1.1.0

### ISSUE THREAD

**Issue by guy032** [vuejs/vuefire#24]
FIREBASE WARNING: Exception was thrown by user callback. TypeError: e.key is not a function
    at n (https://cdn.jsdelivr.net/vuefire/1.1.0/vuefire.min.js:1:575)
    at https://cdn.jsdelivr.net/vuefire/1.1.0/vuefire.min.js:1:1091
    at https://www.gstatic.com/firebasejs/3.0.3/firebase.js:377:375
    at Tb (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:271:165)
    at uc (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:258:215)
    at vc (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:257:1165)
    at pf.g.Hb (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:445:287)
    at kh.g.wd (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:420:251)
    at Ye.wd (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:323:364)
    at rd.fg (https://www.gstatic.com/firebasejs/3.0.3/firebase.js:321:280) 
firebase.js:271 Uncaught TypeError: e.key is not a function

**Comment by posva** [comment]
...
Can you provide a repro or at least a proper stack?

**Comment by Ajusa** [comment]
I am also getting this issue.
`questions: db.ref("questions").orderByChild("topic").equalTo("History"),`
I am trying to bind an array to a query

**Comment by guy032** [comment]
using https://cdn.jsdelivr.net/vuefire/1.2.0/vuefire.min.js
instead of https://cdn.jsdelivr.net/vuefire/1.1.0/vuefire.min.js
fixed it !

**Comment by posva** [comment]
@Ajusa Are you using Vue 2 with vuefire@1.1.0 too?

**Comment by Ajusa** [comment]
I was. I ended up not using VueFire because I didn't need it. Using the latest version of VueFire fixed it for me. Thanks!
